### ISSUE TITLE
Variant=(Short|Long) in adjectival forms

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Lithuanian-ALKSNIS#2]
There is a category Definite=(Ind|Def) for  adjectives, participles etc. in the Lithuanian-HSE and/or Latvian treebanks, but it is Variant=(Short|Long) in Lithuanian-Alksnis.

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_Lithuanian-ALKSNIS/commit/b27c14e99be3fe5b93f036a3241cb272fa7d5f01, https://github.com/UniversalDependencies/UD_Lithuanian-ALKSNIS/commit/a16a7808e410c54da07391537d1ce239d336abbb, and https://github.com/UniversalDependencies/UD_Lithuanian-ALKSNIS/commit/d2fcc09a9fd501493651f90cefa267ae55f11908.
